---
# Source: jupyterhub/templates/scheduling/user-scheduler/rbac.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: release-name-user-scheduler
  labels:
    component: user-scheduler
    app: jupyterhub
    release: release-name
    chart: jupyterhub-3.3.8
    heritage: Helm
subjects:
- kind: ServiceAccount
  name: user-scheduler
  namespace: "default"
roleRef:
  kind: ClusterRole
  name: release-name-user-scheduler
  apiGroup: rbac.authorization.k8s.io
