---
# Source: jupyterhub/templates/image-puller/daemonset-continuous.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: continuous-image-puller
  labels:
    component: continuous-image-puller
    app: jupyterhub
    release: release-name
    chart: jupyterhub-3.3.8
    heritage: Helm
spec:
  selector:
    matchLabels:
      component: continuous-image-puller
      app: jupyterhub
      release: release-name
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  template:
    metadata:
      labels:
        component: continuous-image-puller
        app: jupyterhub
        release: release-name
    spec:
      tolerations:
      - effect: NoSchedule
        key: hub.jupyter.org/dedicated
        operator: Equal
        value: user
      - effect: NoSchedule
        key: hub.jupyter.org_dedicated
        operator: Equal
        value: user
      terminationGracePeriodSeconds: 0
      automountServiceAccountToken: false
      initContainers:
      - name: image-pull-metadata-block
        image: quay.io/jupyterhub/k8s-network-tools:3.3.8
        command:
        - /bin/sh
        - -c
        - echo "Pulling complete"
        securityContext:
          allowPrivilegeEscalation: false
          runAsGroup: 65534
          runAsUser: 65534
      - name: image-pull-singleuser
        image: quay.io/jupyterhub/k8s-singleuser-sample:3.3.8
        command:
        - /bin/sh
        - -c
        - echo "Pulling complete"
        securityContext:
          allowPrivilegeEscalation: false
          runAsGroup: 65534
          runAsUser: 65534
      containers:
      - name: pause
        image: registry.k8s.io/pause:3.9
        securityContext:
          allowPrivilegeEscalation: false
          runAsGroup: 65534
          runAsUser: 65534
