---
# Source: jupyterhub/templates/hub/rbac.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hub
  labels:
    component: hub
    app: jupyterhub
    release: release-name
    chart: jupyterhub-3.3.8
    heritage: Helm
subjects:
- kind: ServiceAccount
  name: hub
  namespace: "default"
roleRef:
  kind: Role
  name: hub
  apiGroup: rbac.authorization.k8s.io
